### ISSUE TITLE
Font Awsome Pro

### ISSUE THREAD

**Issue by sciamano69** [moodle-an-hochschulen/moodle-local_navbarplus#11]
Hi, I want to use Font Awsome Pro Icons but I don't find any description to get them. How I can use them? Can you help me please?
Thank you

**Comment by Kathrin84** [comment]
Hi @sciamano69,

thank you for raising this issue and your question.

We're sticking with the plugin to the implementation of Font Awesome provided by Moodle Core. Currently, Moodle core has Font Awesome 4 (https://fontawesome.com/v4.7.0/) implemented.
The pro icons were introduced with Font Awesome 5.

Even if you have a subscription for the pro icons and add them to your Moodle instance locally, I think you would need to hack this plugin to change the identifier for the new font awesome structure (fas, far and so on) here: https://github.com/moodleuulm/moodle-local_navbarplus/blob/master/lib.php#L76.

As we stick to the Moodle core and furthermore do not use the pro icons for ourselves, I have to admit we have no resources to implement and support the Font Awesome pro icons possibility within this plugin. I'll close this issue therefore as won't fix.

Nevertheless, maybe my comments helped you though for an own solution.

Best, Kathrin
