### ISSUE TITLE
Moodle 4.4.1 compatibility issue

### ISSUE THREAD

**Issue by i11info** [moodle-an-hochschulen/moodle-local_navbarplus#20]
- Install Moodle 4.4.1
- Use the Boost or the latest Boost Union v4.4-r1 theme
- Add addtitional icons
- The additional icons are not aligned properly
![alignment1](https://github.com/user-attachments/assets/ec86467b-4590-4dde-9426-ac99bd7fb816)
- I fixed this issue temporary with this CSS code:
/* Navbar Plus fix */
.navbar-nav {
  height: 60px;
}

Icons are now aligned, but still not perfect. The whole region around icon needs to be clickable, like with other icons. Right now just the icon itself is clickable.

**Comment by abias** [comment]
Hi @i11info ,

thanks for reporting this glitch.
I fixed this for the upcoming 4.4 release in c8805fd. An official release on moodle.org/plugins will follow soon.

Cheers,
Alex
